openapi: 3.0.0
info:
  title: Attus teste técnico mão na massa - Person Management API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
tags:
  - name: person
    description: Person operations
  - name: address
    description: Address operations
paths:
  POST /api/v1/person:
    $ref: './features/person/create-person.yaml'
  PUT /api/v1/person/{personId}:
    $ref: './features/person/update-person.yaml'
  GET /api/v1/person/{personId}:
    $ref: './features/person/find-one-person.yaml'
  GET /api/v1/person:
    $ref: './features/person/find-all-persons.yaml'
  POST /api/v1/address/{personId}:
    $ref: './features/address/create-address.yaml'
  PUT /api/v1/address/{addressId}/person/{personId}:
    $ref: './features/address/update-address.yaml'
  GET /api/v1/address/{addressId}/person/{personId}:
    $ref: './features/address/find-one-address.yaml'
  GET /api/v1/address/person/{personId}:
    $ref: './features/address/find-all-addresses.yaml'