spring:
  profiles:
    active: dev

api:
  endpoint:
    base-url: /api/v1

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    url: /openapi/main.yaml
    path: /api/v1/swagger-ui-doc
