spring:
  profiles:
    active: dev

  web:
    resources:
      add-mappings: false

api:
  endpoint:
    base-url: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,env

server:
  port: 8080