spring:
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate.format_sql: true
      spring.jpa.database-platform: org.hibernate.dialect.PostgresSQLDialect

